### ISSUE TITLE
  casting to pixel for pixelArray() function -   return UnsafeMutablePointer<Pixel>(imageRep.bitmapData)

### ISSUE THREAD

**Issue by johndpope** [AfricanSwift/FilterPlay#2]
![screen shot 2018-08-07 at 3 27 37 pm](https://user-images.githubusercontent.com/289994/43797750-71014f22-9a56-11e8-9a5b-0aa3e955e170.png)
  public func pixelArray() -> UnsafeMutablePointer<Pixel>? {
    // Convert to NSBitmapImageRep For Pixel Access
    guard let imageRep = self.bitmapImageRep() else
    {
      return nil
    }

//    let imageData = UnsafeMutablePointer<Pixel>.alloc(imageRep.bitmapData. * height)
    return UnsafeMutablePointer<Pixel>(imageRep.bitmapData?) // this breaks with latest xcode
  }

the rest of the fixes to get code working are pretty straightforward.
![screen shot 2018-08-07 at 3 27 01 pm](https://user-images.githubusercontent.com/289994/43797733-5ca2b8cc-9a56-11e8-8645-78592c91d088.png)

**Comment by johndpope** [comment]
this might work
```swift
  public func pixelArray() -> UnsafeMutablePointer<Pixel>? {
    // Convert to NSBitmapImageRep For Pixel Access
    guard let imageRep = self.bitmapImageRep() else
    {
      return nil
    }

    //imageRep.bitmapData
    return unsafeBitCast(imageRep.bitmapData, to: UnsafeMutablePointer<Pixel>.self)
  }
```

**Comment by johndpope** [comment]
seems to break the Create empty CGcontext 
![screen shot 2018-08-07 at 3 42 01 pm](https://user-images.githubusercontent.com/289994/43798379-7300f9a6-9a58-11e8-88db-461af2b90821.png)

**Comment by johndpope** [comment]
if I roll back to xcode 8 - I get 

init is unavailable - use withMemoryRebound(to:capactity) to temporarily view  memory as another layout compatible type. so attempting to use this to fix code. although - I'm not sure if I'm going down wrong path.

looking through github  / I found this code
```swift

		do {
			var aMatrix = GLKMatrix4MakePerspective(
				GLKMathDegreesToRadians(76),				/* View angle */
				Float(frameRect.width / frameRect.height),	/* Aspect ratio */
				0.1,										/* Near limit Distance from origin*/
				30)											/* Far limit  */
			withUnsafePointer(to: &aMatrix) { (arr) -> Void in
				arr.withMemoryRebound(to: GLfloat.self, capacity: MemoryLayout<GLKMatrix4>.size / MemoryLayout<GLfloat>.size, { (anArr) -> Void in
					glMultMatrixf(anArr)
				})
			}
		}
```

![screen shot 2018-08-08 at 11 39 51 am](https://user-images.githubusercontent.com/289994/43847925-cfbc81f4-9aff-11e8-9f03-719ee5fa49c5.png)


```swift

    public func pixelArray() -> UnsafeMutablePointer<Pixel>? {
        // Convert to NSBitmapImageRep For Pixel Access
        guard let imageRep = self.bitmapImageRep() else
        {
            return nil
        }
        do{
            if let bitmapData = imageRep.bitmapData{
                bitmapData.withMemoryRebound(to: Pixel.self, capacity: MemoryLayout<Pixel>.size, { (anArr:UnsafeMutablePointer<Pixel>) -> Void in
                    
                    return anArr
                })
            }
            
        }
     
        
        
        return nil
    }
    
```

**Comment by johndpope** [comment]
yielding to this library https://github.com/johndpope/EasyImagy

**Comment by AfricanSwift** [comment]
I've applied the necessary code upgrades for Swift 4. 
Project compiles and runs ok in Xcode 10

**Comment by AfricanSwift** [comment]
BTW you were almost there with the fix:
`imageRep.bitmapData?.withMemoryRebound(to: Pixel.self, capacity: imageRep.pixelsWide * imageRep.pixelsHigh, UnsafeMutablePointer.init)
 `

**Comment by johndpope** [comment]
Thx will take another look for tomorrow.

**Comment by AfricanSwift** [comment]
No worries. 
The code was just an way to start learning Swift, not something I really intended to maintain going forward, so hopefully there's some ideas that can be repurposed.

**Comment by johndpope** [comment]
for some reason a bit of wrangling with forced NSImage.Name() on xcode 9.4 

    let name = imageNames[randomIndex()]
    guard let image = NSImage(named:**NSImage.Name(name)** ) else { return nil   }

great job with this library. 
![glamour](https://user-images.githubusercontent.com/289994/43904181-0e45ebc4-9bbc-11e8-8292-217ea0249597.png)

**Comment by AfricanSwift** [comment]
Probably another issue with the type checker; tends to vary quite a bit between Swift releases.
